#!/bin/sh
# Everything the recorded demos need, written into the gitignored demo/ directory.
#
# demo/ holds private keys and a local database, so it is not in the repository — which
# means the agent config, the file-profile root and the device's own web service have to
# be generated rather than committed. This script is what makes the recordings in
# mint/demos/ reproducible from a clean checkout.
#
# Run it once, with the gateway already up (`cd demo && ../oarlockd -config ./oarlock.local.yaml`).
set -eu
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT/demo"
API=http://127.0.0.1:8443/api/v1
TOKEN=dev-token-long-enough-for-the-check
DEV=treadmill-4821

mkdir -p device-files device-web

cat > device-files/README.txt <<'TXT'
This directory is the `file` profile's confined root on the device.
Confinement below it is the kernel's job (os.Root); the root itself is a policy choice.
TXT
printf 'model=treadmill-4821\nfirmware=2.4.1\nlast_service=2026-08-30\n' > device-files/device.conf
printf '2026-09-11T15:00:00Z belt_speed=0\n2026-09-11T15:01:00Z belt_speed=4.2\n2026-09-11T15:02:00Z fault=E07 belt_stall\n' > device-files/session.log

cat > device-web/index.html <<'TXT'
<!doctype html><title>treadmill-4821 · on-device console</title>
<h1>treadmill-4821</h1>
<p>This page is served by the device on 127.0.0.1:3000.</p>
<p>It has no authentication, because it was never meant to leave the device.</p>
TXT

cat > agent.demo.yaml <<'TXT'
# Generated by mint/demos/00-setup.sh. A local agent offering all four profiles.
# The real device form is documented at android/system/agent.conf.example.
gateway: ws://127.0.0.1:8443/ws/control
device: treadmill-4821
key: ./device.key
shell: /bin/sh
insecure_skip_pin: true

# Complete argvs, matched element for element. Not "this program with any arguments".
exec:
  - ["/usr/bin/uptime"]
  - ["/bin/date", "-u"]
  - ["/usr/bin/sw_vers", "-productVersion"]
exec_timeout: 30s

file_root: ./device-files
file_writable: true

forward_ports:
  - 3000
forward_dial_timeout: 5s
TXT

# The device must advertise the profiles the agent offers, and the grant must cover them.
curl -fsS -X PUT "$API/devices/$DEV" -H "Authorization: Bearer $TOKEN" -H 'Content-Type: application/json' \
  -d "{\"id\":\"$DEV\",\"platform\":\"android\",\"mode\":\"dispatch\",\"keys\":[\"$(cat device.key.pub)\"],\"profiles\":[\"shell\",\"exec\",\"file\",\"tcp\"]}" >/dev/null
curl -fsS -X PUT "$API/permissions/operator-shell" -H "Authorization: Bearer $TOKEN" -H 'Content-Type: application/json' \
  -d '{"id":"operator-shell","name":"Operator shell","principals":["*@oncall.example.com","admin@mail.com"],"devices":["treadmill-*","samsung-s23"],"actions":["shell","exec","file:read","file:write","tcp"],"effect":"allow","enabled":true}' >/dev/null

printf 'demo/ is ready.\n\n'
printf 'Now, in two more terminals:\n'
printf '  cd demo && python3 -m http.server 3000 --bind 127.0.0.1 --directory ./device-web\n'
printf '  cd demo && ../oarlock-agent -config ./agent.demo.yaml\n'
