// Package openapi generates the API's OpenAPI 3.1 document from the route table.
//
// E7.S1: generated from the handlers, with drift failing the build. The failure it exists
// to prevent is a document describing an API the gateway no longer has — an SDK built from
// a stale spec compiles and then 404s in production, which is the worst place to find out.
//
// # What is generated and what is written
//
// Paths, methods, operation ids, parameters, security and the authorisation each endpoint
// checks come from `apisrv.Routes()`, so they cannot disagree with the mux — the mux is
// built from the same table.
//
// Schemas are written by hand, here, against the response structs. Inferring them would
// need annotations on every struct and the annotations would become the thing that drifted.
// Writing them here at least puts them next to a test that renders a real response and
// compares the field names, which is the check that catches the mistake that matters.
//
// # This is not a live-reflection tool
//
// The document is a file in the repository, regenerated by a command and checked by a test
// — the same shape `tokens/generate.mjs` and `pnpm tokens:check` already use for design
// tokens. A generator that ran at startup would produce a document nobody could review in
// a diff, and the diff is most of the value: an endpoint appearing in a pull request is
// something a person should see.
package openapi

import (
	"bytes"
	"fmt"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/oarlock/oarlock/internal/apisrv"
)

// Version is the document's version, and it is the *API's* version rather than the
// gateway's build.
//
// `0.0.0` on purpose while the API is unstable: README says there are no releases and no
// API stability, and a document claiming 1.0 would be the first place somebody read
// otherwise.
const Version = "0.0.0"

// Generate returns the document as YAML.
func Generate() ([]byte, error) {
	doc := document{
		OpenAPI: "3.1.0",
		Info: info{
			Title:   "Oarlock",
			Version: Version,
			Summary: "Gateway-terminated SSH for machines you cannot dial.",
			Description: strings.TrimSpace(`
This document is generated from the gateway's route table and checked by a test; it cannot
describe an endpoint the gateway does not serve.

**Endpoints marked optional are absent unless the deployment configured what they need.**
An API replica that serves attach-ticket renewals but cannot open sessions is a supported
shape, and such a gateway answers 404 for the endpoints it does not have rather than
pretending to have them and refusing.

Every response that is not a success is an RFC 9457 problem document. The ` + "`request`" + `
field is a correlation id: quoting it is how somebody gets help.
`),
			License: &license{Name: "Apache-2.0", Identifier: "Apache-2.0"},
		},
		Servers: []server{{
			URL:         "https://{host}",
			Description: "The gateway's HTTP listener.",
			Variables: map[string]serverVar{
				"host": {Default: "gateway.example.org", Description: "Your gateway."},
			},
		}},
		Security: []map[string][]string{{"bearerAuth": {}}},
		Paths:    map[string]pathItem{},
		Components: components{
			SecuritySchemes: map[string]securityScheme{
				"bearerAuth": {
					Type: "http", Scheme: "bearer",
					Description: "The token your authenticator issues. Never a query " +
						"parameter: a query string ends up in ingress logs.",
				},
			},
			Schemas: schemas(),
		},
	}

	for _, r := range apisrv.Routes() {
		item := doc.Paths[r.Path]
		op := &operation{
			OperationID: r.OperationID,
			Summary:     r.Summary,
			Description: describe(r),
			Tags:        []string{tagFor(r.Path)},
			Parameters:  parametersFor(r),
			Responses:   responsesFor(r),
		}
		switch r.Method {
		case "GET":
			item.Get = op
		case "POST":
			item.Post = op
		case "PUT":
			item.Put = op
		case "DELETE":
			item.Delete = op
		default:
			return nil, fmt.Errorf("openapi: no slot for method %q on %s", r.Method, r.Path)
		}
		doc.Paths[r.Path] = item
	}

	var buf bytes.Buffer
	buf.WriteString("# Generated by `go run ./cmd/oarlock-openapi`. Do not edit.\n")
	buf.WriteString("#\n")
	buf.WriteString("# Paths and operations come from internal/apisrv's route table, so this\n")
	buf.WriteString("# cannot describe an endpoint the gateway does not serve. Schemas are\n")
	buf.WriteString("# written by hand in internal/openapi and checked against real responses.\n")
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(doc); err != nil {
		return nil, err
	}
	if err := enc.Close(); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// describe says what a reader needs beyond the summary: what it costs them to call it, and
// whether their gateway has it.
func describe(r apisrv.RouteInfo) string {
	var b strings.Builder
	if r.Action != "" {
		fmt.Fprintf(&b, "Requires the `%s` action. ", r.Action)
	} else {
		b.WriteString("Scoped by the caller's own identity rather than by a grant. ")
	}
	if r.Optional {
		fmt.Fprintf(&b, "**Optional:** present only when the gateway is configured with %s; "+
			"otherwise this path answers 404.", r.Requires)
	}
	return strings.TrimSpace(b.String())
}

// tagFor groups operations the way somebody reading looks for them.
func tagFor(path string) string {
	rest := strings.TrimPrefix(path, apisrv.Prefix+"/")
	if i := strings.IndexByte(rest, '/'); i >= 0 {
		rest = rest[:i]
	}
	if rest == "" {
		return "gateway"
	}
	return rest
}

// parametersFor derives path parameters from the wildcards, plus the paging and filtering
// a list takes.
func parametersFor(r apisrv.RouteInfo) []parameter {
	var out []parameter
	for _, seg := range strings.Split(r.Path, "/") {
		if name, ok := strings.CutPrefix(seg, "{"); ok {
			out = append(out, parameter{
				Name: strings.TrimSuffix(name, "}"), In: "path", Required: true,
				Schema:      &schema{Type: "string"},
				Description: "The resource's id.",
			})
		}
	}
	// The one endpoint that does real work a client might do twice. Named here for the
	// same reason as the paging parameters below: the alternative is every SDK author
	// discovering it from prose, and a retry that opens a second shell is the failure
	// this header exists to prevent.
	if r.OperationID == "openSession" {
		out = append(out, parameter{
			Name: "Idempotency-Key", In: "header", Schema: &schema{Type: "string"},
			Description: "An opaque key the client chooses, at most 255 bytes. " +
				"A retry carrying the same key returns the session the first request " +
				"opened, with a freshly minted attach ticket, and answers 200 rather " +
				"than 201. The same key with a different body is refused as " +
				"`idempotency_key_reused`; a retry that arrives while the first is " +
				"still running is refused as `idempotency_in_flight` and is retryable.",
		})
	}

	// The state a session is in changes on its own, so the useful read is usually the
	// *next* one. Named here because an SDK cannot long-poll an endpoint whose spec
	// does not admit the parameters.
	if r.OperationID == "getSession" {
		out = append(out,
			parameter{Name: "wait", In: "query", Schema: &schema{Type: "string"},
				Description: "Hold the request until the session's state changes, as a " +
					"Go duration such as `30s`. Clamped to 60s. Absent or `0` answers " +
					"immediately. A wait that expires is still a 200 with the unchanged " +
					"session: \"still the same\" is an answer, not an error."},
			parameter{Name: "state", In: "query", Schema: &schema{Type: "string"},
				Description: "The state you already have. With it, a transition that " +
					"happened between your last read and this request is reported " +
					"immediately instead of being missed; without it, the wait is " +
					"relative to whatever the state is when the request arrives."},
		)
	}

	// Listing endpoints page with a cursor. Named here rather than inferred, because the
	// alternative was every SDK author discovering it from a header.
	if r.Method == "GET" && !strings.Contains(r.Path, "{") &&
		(strings.HasSuffix(r.Path, "/sessions") || strings.HasSuffix(r.Path, "/devices") ||
			strings.HasSuffix(r.Path, "/permissions")) {
		out = append(out,
			parameter{Name: "cursor", In: "query", Schema: &schema{Type: "string"},
				Description: "The `next_cursor` from the previous page. Absent means the first."},
			parameter{Name: "limit", In: "query", Schema: &schema{Type: "integer"},
				Description: "Page size. The gateway may return fewer."},
		)
	}

	// The session list can be bounded by when a session was created. Named here rather
	// than left to prose, because which end of the range is inclusive is exactly the
	// kind of thing an SDK author guesses wrong without the spec saying so.
	if r.OperationID == "listSessions" {
		out = append(out,
			parameter{Name: "since", In: "query", Schema: &schema{Type: "string"},
				Description: "Only sessions created at or after this instant, RFC 3339 " +
					"(e.g. `2026-06-01T00:00:00Z`). Half-open together with `until`: " +
					"`since` is inclusive."},
			parameter{Name: "until", In: "query", Schema: &schema{Type: "string"},
				Description: "Only sessions created before this instant, RFC 3339. " +
					"Half-open together with `since`: `until` is exclusive, so two " +
					"adjacent ranges never overlap and a boundary instant belongs to " +
					"only one of them."},
		)
	}
	return out
}

// responsesFor gives every operation the same failure vocabulary, because it has one.
func responsesFor(r apisrv.RouteInfo) map[string]response {
	out := map[string]response{
		"401": problemResponse("The credential was missing or refused."),
		"429": problemResponse("Rate limited. `Retry-After` says how long."),
		"500": problemResponse("The gateway failed. `request` is the correlation id."),
	}
	if r.Action != "" {
		out["403"] = problemResponse("The authorizer refused, or could not be reached — " +
			"`type` distinguishes `not_authorized` from `authz_unavailable`, and they " +
			"mean different things.")
	}
	if strings.Contains(r.Path, "{") {
		out["404"] = problemResponse("No such resource, or the caller may not see it. " +
			"Deliberately the same answer for both: telling them apart is an " +
			"enumeration oracle.")
	}
	switch r.Method {
	case "POST":
		out["201"] = response{Description: "Created.",
			Content: jsonContent(schemaFor(r))}
		out["200"] = response{Description: "Done.", Content: jsonContent(schemaFor(r))}
		out["400"] = problemResponse("The request body was not valid.")
	case "DELETE":
		out["204"] = response{Description: "Done. No body."}
	default:
		out["200"] = response{Description: "OK.", Content: jsonContent(schemaFor(r))}
	}
	return out
}

func problemResponse(desc string) response {
	return response{
		Description: desc,
		Content: map[string]mediaType{
			"application/problem+json": {Schema: &schema{Ref: "#/components/schemas/Problem"}},
		},
	}
}

func jsonContent(s *schema) map[string]mediaType {
	if s == nil {
		return nil
	}
	return map[string]mediaType{"application/json": {Schema: s}}
}

// schemaFor names the response body where this package knows it.
//
// Nil where it does not, which renders as a response with no schema — honest, and visibly
// incomplete to anybody generating an SDK. Inventing a shape would be worse: a generated
// client with a field the gateway never sends fails at runtime rather than at generation.
func schemaFor(r apisrv.RouteInfo) *schema {
	ref := func(n string) *schema { return &schema{Ref: "#/components/schemas/" + n} }
	switch r.OperationID {
	case "listSessions":
		return ref("SessionList")
	case "getSession", "openSession":
		return ref("Session")
	case "listDevices":
		return ref("DeviceList")
	case "getDevice", "createDevice", "replaceDevice":
		return ref("Device")
	case "listAgents":
		return ref("AgentList")
	case "getRecording":
		return ref("Recording")
	}
	return nil
}

// sortedPaths is not needed for correctness — yaml.v3 sorts map keys — but the assertion is
// cheap and the day it stops being true the document's diff becomes unreadable.
func sortedPaths(paths map[string]pathItem) []string {
	out := make([]string, 0, len(paths))
	for k := range paths {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}
