// The integrity verdict's copy, checked against recordings the gateway actually produced
// and then actually damaged.
//
// tests/fixtures/recordings/verdicts.json is generated by internal/record: real
// recordings, truncated and edited and re-keyed in the specific ways the verifier
// distinguishes, with the verdict *computed* by the verifier rather than written out by
// hand. That last part matters — expectations written here would test my beliefs about
// what a truncation looks like instead of what one is.

import { test, expect } from "@playwright/test";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { describe, type Verdict } from "@oarlock/terminal/verdict";

interface Fixture {
  name: string;
  status: string;
  ok: boolean;
  events_found: number;
  events_expected: number;
  last_good_checkpoint: number;
  note: string;
}

const fixtures = (
  JSON.parse(
    readFileSync(
      fileURLToPath(new URL("../fixtures/recordings/verdicts.json", import.meta.url)),
      "utf8",
    ),
  ) as { recordings: Fixture[] }
).recordings;

const byName = new Map(fixtures.map((f) => [f.name, f]));

test("the fixtures cover every status the verifier can return", () => {
  const statuses = new Set(fixtures.map((f) => f.status));
  // If the verifier gains a status and the fixtures do not, the component has copy for a
  // verdict nobody has ever seen it produce.
  for (const want of ["valid", "truncated", "altered", "bad_signature", "malformed"]) {
    expect(statuses.has(want), `no fixture produces ${want}`).toBe(true);
  }
  expect(fixtures.length).toBeGreaterThan(5);
});

test("only an intact recording is described as intact", () => {
  for (const f of fixtures) {
    const c = describe(f as Verdict);
    if (f.ok) {
      expect(c.tone, f.name).toBe("trusted");
    } else {
      // The property that matters most: nothing about a damaged recording may read as a
      // confirmation. A player that shows a tampered recording like an intact one is a
      // player that launders it.
      expect(c.tone, f.name).not.toBe("trusted");
      expect(c.headline.toLowerCase(), `${f.name}: "${c.headline}"`).not.toContain("is intact");
    }
  }
});

test("a truncation is not described as tampering", () => {
  // Different next actions: a recording that ends early usually means a process died,
  // and is often still useful. One that was edited is a different conversation.
  const t = describe(byName.get("truncated") as Verdict);
  expect(t.tone).toBe("partial");
  expect(`${t.headline} ${t.body}`.toLowerCase()).not.toContain("tamper");

  const a = describe(byName.get("altered") as Verdict);
  expect(a.tone).toBe("broken");
  expect(`${a.headline} ${a.body}`.toLowerCase()).toContain("tamper");
  expect(a.headline).not.toBe(t.headline);
});

test("a truncation past a checkpoint says how much survived", () => {
  // The field that turns "this file is wrong" into "intact up to event 128 and then
  // stops". A five-event recording never reaches a checkpoint, which is why the fixtures
  // include a long one.
  const f = byName.get("truncated-after-checkpoint")!;
  expect(f.last_good_checkpoint).toBeGreaterThan(0);
  const c = describe(f as Verdict);
  expect(c.body).toContain(String(f.last_good_checkpoint));
  expect(c.body).toContain(String(f.events_found));
  expect(c.body).toContain(String(f.events_expected));

  // And a truncation *before* the first checkpoint says so, rather than claiming a
  // verified prefix it cannot demonstrate.
  const short = describe(byName.get("truncated") as Verdict);
  expect(short.body).toContain("before the first checkpoint");
});

test("a bad signature is not described as tampering either", () => {
  // It may simply be a recording from another deployment. Saying "somebody edited this"
  // would be an accusation the verdict cannot support.
  const c = describe(byName.get("bad-signature") as Verdict);
  expect(c.tone).toBe("broken");
  expect(`${c.headline} ${c.body}`.toLowerCase()).not.toContain("edited");
  expect(c.body.toLowerCase()).toContain("different deployment");
});

test("every status gets its own words", () => {
  const heads = new Map<string, string>();
  for (const f of fixtures) {
    const c = describe(f as Verdict);
    const prev = heads.get(c.headline);
    if (prev && prev !== f.status) {
      throw new Error(`${prev} and ${f.status} share a headline: "${c.headline}"`);
    }
    heads.set(c.headline, f.status);
  }
  expect(heads.size).toBeGreaterThanOrEqual(5);
});

test("an unknown status withholds the claim of integrity", () => {
  // A verifier newer than this client is a reason not to vouch for a recording, never a
  // reason to imply it is fine.
  const c = describe({ status: "invented_next_year", ok: false });
  expect(c.tone).toBe("broken");
  expect(c.body).toContain("invented_next_year");
  expect(c.headline.toLowerCase()).not.toContain("intact");
});

test("a verdict claiming valid without ok is treated as unverified", () => {
  // A contradiction about integrity resolves pessimistically. The alternative is a
  // component that can be talked into a green banner by a malformed response.
  const c = describe({ status: "valid", ok: false });
  expect(c.tone).toBe("broken");
  expect(c.headline.toLowerCase()).not.toContain("is intact");
});

test("no verdict at all is unverified, not fine", () => {
  const c = describe({ status: "", ok: false });
  expect(c.tone).toBe("broken");
  expect(c.headline.toLowerCase()).not.toContain("intact");
});
